name: Docker Compose Image CI

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: get_tag
      run: |
        TAG=$(basename ${GITHUB_REF})
        echo "::set-output name=TAG::$TAG"
    - name: Build Docker-Compose image
      run: docker-compose --file docker-compose-build.yml build --build-arg Version=${{ steps.get_tag.outputs.TAG }}
