name: Docker Image CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build . --file ./allinone/Dockerfile --tag jumpserver/jms_all:dev
    - name: Logo into registry
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u fit2bot --password-stdin
    - name: Push image
      run: docker push jumpserver/jms_all:dev
